import streamlit as st
import pandas as pd

st.set_page_config(page_title='Home', page_icon='🏠')
st.title("diff_viz Dashboard \U0001F4CA")

st.header('diff_viz: Your One Stop Shop for MPT Plots!')


st.markdown("""
    [diff_viz](https://diff-viz.readthedocs.io/en/latest/] is a Python package that allows you to visualize and analyze your MPT data.
    This dashboard allows you to upload your data and generate plots with just a few clicks!

    The goal of this package is to allow researchers working with Multiple Particle Tracking (MPT) data to quickly generate informative data visualizations.

    Specifically, this package will enable users to:

    - Automatically generate plots for exploratory data analysis

    - Create publication-worthy plots

    - Build on template plots to create visualizations for new use cases

    ## Getting Started
    ### File Uploader
    To get started, upload your data as a CSV using the file uploader. Data can be in the following categories:

    1) MSD Trajectory data

        This is typically the data that is produced by running MPT videos through ImageJ and Trackmate. 
        Files for MSD Trajectory data should have the following columns:
        - 'Track_ID' for the particle ID
        - 'X' for the x-coordinate
        - 'Y' for the y-coordinate
        - 'Frame' for the frame number
        - 'MSD' for the mean squared displacement

    2) Trajectory Features data

        This data can be generated by running MSD trajectory data through diff_classifier. It should at least include:
        - 'Track_ID' for the particle ID
        - 'alpha' for the exponent of the anomalous diffusion equation
        - 'D_fit' for the fitted diffusion coefficient of the anomalous diffusion equation
        - 'Deff1' for the effective diffusion coefficient at 0.33s

        
    3) Geomean or Geosem data

""")